//
//  Epilogue.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using Simpl.Serialization;

namespace Simpl.OODSS.Logging
{
    /// <summary>
    /// missing java doc comments or could not find the source file.
    /// </summary>
    public class Epilogue : ElementState
    {
    }
}