//
//  Prologue.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using ecologylab.serialization;

namespace Simpl.OODSS.Logging
{
    /// <summary>
    /// missing java doc comments or could not find the source file.
    /// </summary>
    public class Prologue : ElementState
    {
        /// <summary>
        /// missing java doc comments or could not find the source file.
        /// </summary>
        [SimplScalar] private String _date;

        /// <summary>
        /// missing java doc comments or could not find the source file.
        /// </summary>
        [SimplScalar] private String _ip;

        /// <summary>
        /// missing java doc comments or could not find the source file.
        /// </summary>
        [SimplScalar] private String _questionId;

        /// <summary>
        /// missing java doc comments or could not find the source file.
        /// </summary>
        [SimplScalar] private String _questionPath;

        /// <summary>
        /// missing java doc comments or could not find the source file.
        /// </summary>
        [SimplScalar] private String _studyName;

        /// <summary>
        /// missing java doc comments or could not find the source file.
        /// </summary>
        [SimplScalar] private String _userId;

        public String Date
        {
            get { return _date; }
            set { _date = value; }
        }

        public String Ip
        {
            get { return _ip; }
            set { _ip = value; }
        }

        public String UserID
        {
            get { return _userId; }
            set { _userId = value; }
        }

        public String QuestionId
        {
            get { return _questionId; }
            set { _questionId = value; }
        }

        public String StudyName
        {
            get { return _studyName; }
            set { _studyName = value; }
        }

        public String QuestionPath
        {
            get { return _questionPath; }
            set { _questionPath = value; }
        }
    }
}