//
//  Epilogue.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;

namespace ecologylab.oodss.logging 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class Epilogue : ElementState
	{
	}
}
