//
//  LogEvent.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.oodss.messages;
using System.Text;

namespace ecologylab.oodss.logging 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
    public class LogEvent : RequestMessage<ServiceMessage<object>>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		[simpl_hints(new Hint[] { Hint.XML_LEAF_CDATA })]
		private StringBuilder bufferToLog;

		public LogEvent()
		{ }

		public StringBuilder BufferToLog
		{
			get{return bufferToLog;}
			set{bufferToLog = value;}
		}
	}
}
