//
//  Prologue.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;
using ecologylab.serialization;

namespace ecologylab.oodss.logging 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class Prologue : ElementState
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String date;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String ip;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String userID;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String questionId;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String studyName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String questionPath;

		public Prologue()
		{ }

		public String Date
		{
			get{return date;}
			set{date = value;}
		}

		public String Ip
		{
			get{return ip;}
			set{ip = value;}
		}

		public String UserID
		{
			get{return userID;}
			set{userID = value;}
		}

		public String QuestionId
		{
			get{return questionId;}
			set{questionId = value;}
		}

		public String StudyName
		{
			get{return studyName;}
			set{studyName = value;}
		}

		public String QuestionPath
		{
			get{return questionPath;}
			set{questionPath = value;}
		}
	}
}
