//
//  SendPrologue.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using ecologylab.attributes;

namespace ecologylab.oodss.logging 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class SendPrologue : LogueMessage
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String date;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String ip;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String userID;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private String studyName;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private Boolean performEpilogueNow;

		public SendPrologue()
		{ }

		public String Date
		{
			get{return date;}
			set{date = value;}
		}

		public String Ip
		{
			get{return ip;}
			set{ip = value;}
		}

		public String UserID
		{
			get{return userID;}
			set{userID = value;}
		}

		public String StudyName
		{
			get{return studyName;}
			set{studyName = value;}
		}

		public Boolean PerformEpilogueNow
		{
			get{return performEpilogueNow;}
			set{performEpilogueNow = value;}
		}
	}
}
