//
//  CloseMessage.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using Simpl.Serialization.Attributes;
using ecologylab.collections;

namespace Simpl.OODSS.Messages
{
    /// <summary>
    /// missing java doc comments or could not find the source file.
    /// </summary>
    [SimplInherit]
    public class CloseMessage : RequestMessage
    {
        public override ResponseMessage PerformService(Scope<object> clientSessionScope)
        {
            throw new System.NotImplementedException();
        }
    }
}