//
//  HttpRequest.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;
using Simpl.Fundamental.Net;
using ecologylab.serialization;

namespace ecologylab.oodss.messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
    public class HttpRequest : RequestMessage<ServiceMessage<object>>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private ParsedUri okResponseUrl;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[simpl_scalar]
		private ParsedUri errorResponseUrl;

		public HttpRequest()
		{ }

		public ParsedUri OkResponseUrl
		{
			get{return okResponseUrl;}
			set{okResponseUrl = value;}
		}

		public ParsedUri ErrorResponseUrl
		{
			get{return errorResponseUrl;}
			set{errorResponseUrl = value;}
		}
	}
}
