//
//  OkResponse.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using System.Collections.Generic;

namespace ecologylab.oodss.messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class OkResponse : ResponseMessage<ServiceMessage<object>>
	{
		public OkResponse()
		{ }
	}
}
