//
//  UpdateMessage.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using ecologylab.oodss.messages;

namespace Simpl.OODSS.Messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[simpl_inherit]
	public class UpdateMessage<S> : ServiceMessage<S>
	{
		public UpdateMessage()
		{ }
	}
}
