//
//  ServiceMessage.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;

namespace Simpl.OODSS.Messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	public class ServiceMessage<S> : ElementState
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplScalar]
		private Int64 _timeStamp;

		public ServiceMessage()
		{ }

		public Int64 TimeStamp
		{
			get{return _timeStamp;}
			set{_timeStamp = value;}
		}
	}
}
