//
//  UrlMessage.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using System;
using Simpl.Serialization.Attributes;

namespace Simpl.OODSS.Messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
    public class UrlMessage : RequestMessage<ServiceMessage<object>>
	{
		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplScalar]
		private String url;

		/// <summary>
		/// missing java doc comments or could not find the source file.
		/// </summary>
		[SimplScalar]
		private String _collection;

		public UrlMessage()
		{ }

		public String Url
		{
			get{return url;}
			set{url = value;}
		}

		public String Collection
		{
			get{return _collection;}
			set{_collection = value;}
		}
	}
}
