//
//  HttpGetRequest.cs
//  s.im.pl serialization
//
//  Generated by DotNetTranslator on 04/09/11.
//  Copyright 2011 Interface Ecology Lab. 
//

using Simpl.Serialization.Attributes;
using ecologylab.oodss.messages;

namespace Simpl.OODSS.Messages 
{
	/// <summary>
	/// missing java doc comments or could not find the source file.
	/// </summary>
	[SimplInherit]
	public class HttpGetRequest : HttpRequest
	{
		public HttpGetRequest()
		{ }
	}
}
